# System-wide .bashrc file for interactive bash(1) shells.

# if not running interactively, don't do anything
[ -z "$PS1" ] && return

export PS1='\[\033[1m\]\u@\h:\w$\[\033[m\] '

# make bash check its window size after a process completes
shopt -s checkwinsize

# history parameters
export HISTCONTROL=ignoreboth
export HISTSIZE=500
