set nocompatible
set t_Co=256
set shiftround
set incsearch
set scrolloff=2
set autoindent
set smartindent
set tabstop=2
set expandtab
set shiftwidth=2
set showmatch
set filetype=on
set nocompatible
set nopaste
set pastetoggle=<f11>
set number
set hlsearch
set incsearch
syntax enable
